[log]
level = "error" # trace, debug, info, warn, error, none
outfile = "log.log"
format = "fileline" # fileline, target, json

[perception_service]
ip = "127.0.0.1"
port = "8000"
heartbeat_interval = 90 # Seconds

[application_service]
ip = "127.0.0.1"
port = "8000"

[redis]
ip = "127.0.0.1"
port = "6379"

[middleware]
redis_cluster = ["", ""]
port = ""


[alarm]
edge_trigger = ["error", "warn"]
notifymails = ["paradoxt@gmail.com"]


