[log]
level = "warn"          # trace, debug, info, warn, error, none
outfile = "log.log"
format = "fileline"      # fileline, target, json

[perception_service]
ip = "0.0.0.0"
port = "8900"
heartbeat_interval = 120  # Seconds

[redis]
ip = "127.0.0.1"
port = "6379"

[alarm]
edge_trigger = ["error", "warn"]
notifymails = ["paradoxt@gmail.com"]


